/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import emanuellynogueiratrizotti.dao.ProdutoDAO;
import emanuellynogueiratrizotti.model.Produto;
import java.awt.CardLayout;
import java.awt.HeadlessException;

/**
 *
 * @author emanuelly
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        carregarTabela();
        carregarTabelaFuncionarios();
        carregarTabelaMesas();
        preencherCombosEstrangeiros();
        carregarTabelaComandas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanelCom = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbMesaComanda = new javax.swing.JComboBox<>();
        cmbGarcomComanda = new javax.swing.JComboBox<>();
        cmbCaixaComanda = new javax.swing.JComboBox<>();
        cmbStatusComanda = new javax.swing.JComboBox<>();
        cmbPgtoComanda = new javax.swing.JComboBox<>();
        txtGorjetaComanda = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton11 = new javax.swing.JButton();
        txtValorFiltro = new javax.swing.JTextField();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jScrollBar4 = new javax.swing.JScrollBar();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblComandas = new javax.swing.JTable();
        lblComandasAbertas = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanelFun = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtNomeFun = new javax.swing.JTextField();
        txtIdadeFun = new javax.swing.JTextField();
        cmbCargoFun = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollBar2 = new javax.swing.JScrollBar();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblFuncionarios = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanelMes = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtNumeroMesa = new javax.swing.JTextField();
        cmbStatusMesa = new javax.swing.JComboBox<>();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollBar3 = new javax.swing.JScrollBar();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMesas = new javax.swing.JTable();
        cmbFiltroMesa = new javax.swing.JComboBox<>();
        lblMesasDisponiveis = new javax.swing.JLabel();
        jPanelPro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtPreco = new javax.swing.JTextField();
        cmbCategoria = new javax.swing.JComboBox<>();
        txtTempo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProdutos = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();

        jTextField3.setText("jTextField3");

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Comandas");

        cmbMesaComanda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        cmbGarcomComanda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        cmbCaixaComanda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cmbCaixaComanda.addActionListener(this::cmbCaixaComandaActionPerformed);

        cmbStatusComanda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "ABERTA", "FECHADA" }));

        cmbPgtoComanda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione ", "Dinheiro", "Cartão", "PIX" }));
        cmbPgtoComanda.addActionListener(this::cmbPgtoComandaActionPerformed);

        txtGorjetaComanda.addActionListener(this::txtGorjetaComandaActionPerformed);

        jLabel15.setText("Mesa");

        jLabel16.setText("Garçom");

        jLabel17.setText("Caixa");

        jLabel18.setText("Status");

        jLabel19.setText("Forma Pgto");

        jLabel20.setText("Gorjeta");

        jButton11.setText("Filtrar");
        jButton11.addActionListener(this::jButton11ActionPerformed);

        txtValorFiltro.setColumns(10);
        txtValorFiltro.addActionListener(this::txtValorFiltroActionPerformed);

        jButton12.setText("Gerenciar Itens");
        jButton12.addActionListener(this::jButton12ActionPerformed);

        jButton13.setText("Excluir");
        jButton13.addActionListener(this::jButton13ActionPerformed);

        jButton14.setText("Editar");
        jButton14.addActionListener(this::jButton14ActionPerformed);

        jButton15.setText("Abrir");
        jButton15.addActionListener(this::jButton15ActionPerformed);

        jLabel21.setFont(new java.awt.Font("Liberation Sans", 0, 12)); // NOI18N
        jLabel21.setText("( -> Listar comandas acima de: )");

        tblComandas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "IDMesa", "Status", "Pgto", "Gorjeta"
            }
        ));
        tblComandas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblComandasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblComandas);

        lblComandasAbertas.setText("jLabel22");

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pitica.png"))); // NOI18N
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton16.setText("Join");
        jButton16.addActionListener(this::jButton16ActionPerformed);

        javax.swing.GroupLayout jPanelComLayout = new javax.swing.GroupLayout(jPanelCom);
        jPanelCom.setLayout(jPanelComLayout);
        jPanelComLayout.setHorizontalGroup(
            jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComLayout.createSequentialGroup()
                .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelComLayout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jLabel1)
                        .addGap(249, 249, 249)
                        .addComponent(jButton16))
                    .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanelComLayout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelComLayout.createSequentialGroup()
                                    .addComponent(jLabel21)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblComandasAbertas))
                                .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanelComLayout.createSequentialGroup()
                                        .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbMesaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel15))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbGarcomComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel16))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbCaixaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel17))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbStatusComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel18))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbPgtoComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel19))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel20)
                                            .addComponent(txtGorjetaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanelComLayout.createSequentialGroup()
                                        .addComponent(jButton11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtValorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jButton15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton12)))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelComLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar4, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelComLayout.setVerticalGroup(
            jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelComLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jButton16))
                .addGap(8, 8, 8)
                .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMesaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbGarcomComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCaixaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbStatusComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbPgtoComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtGorjetaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton11)
                    .addComponent(txtValorFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton12)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(jButton15)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(lblComandasAbertas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelComLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelComLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollBar4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanel1.add(jPanelCom, "telaComandas");

        jLabel2.setText("Funcionários");

        txtIdadeFun.addActionListener(this::txtIdadeFunActionPerformed);

        cmbCargoFun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Caixa", "Cozinheiro", "Garçom" }));

        jLabel10.setText("Nome");

        jLabel11.setText("Idade");

        jLabel12.setText("Cargo");

        tblFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Idade", "Cargo"
            }
        ));
        tblFuncionarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFuncionariosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblFuncionarios);

        jButton5.setText("Salvar");
        jButton5.addActionListener(this::jButton5ActionPerformed);

        jButton6.setText("Editar");
        jButton6.addActionListener(this::jButton6ActionPerformed);

        jButton7.setText("Excluir");
        jButton7.addActionListener(this::jButton7ActionPerformed);

        javax.swing.GroupLayout jPanelFunLayout = new javax.swing.GroupLayout(jPanelFun);
        jPanelFun.setLayout(jPanelFunLayout);
        jPanelFunLayout.setHorizontalGroup(
            jPanelFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFunLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNomeFun)
                    .addGroup(jPanelFunLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtIdadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(12, 12, 12)
                .addGroup(jPanelFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(cmbCargoFun, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69))
            .addGroup(jPanelFunLayout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelFunLayout.createSequentialGroup()
                .addGroup(jPanelFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelFunLayout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(jButton5)
                        .addGap(27, 27, 27)
                        .addComponent(jButton6)
                        .addGap(23, 23, 23)
                        .addComponent(jButton7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar2, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
        );
        jPanelFunLayout.setVerticalGroup(
            jPanelFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFunLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addGroup(jPanelFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCargoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelFunLayout.createSequentialGroup()
                        .addComponent(jScrollBar2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelFunLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(jPanelFunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jButton6)
                            .addComponent(jButton7))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3)
                        .addContainerGap())))
        );

        jPanel1.add(jPanelFun, "telaFuncionarios");

        jLabel4.setText("Mesas");

        cmbStatusMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Disponível", "Ocupada", "Reservada" }));

        jButton8.setText("Salvar");
        jButton8.addActionListener(this::jButton8ActionPerformed);

        jButton9.setText("Editar");
        jButton9.addActionListener(this::jButton9ActionPerformed);

        jButton10.setText("Excluir");
        jButton10.addActionListener(this::jButton10ActionPerformed);

        jLabel13.setText("Número");

        jLabel14.setText("Status");

        tblMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Número", "Status"
            }
        ));
        tblMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMesasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMesas);

        cmbFiltroMesa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todas", "Disponível", "Ocupada", "Reservada" }));
        cmbFiltroMesa.addActionListener(this::cmbFiltroMesaActionPerformed);

        lblMesasDisponiveis.setForeground(new java.awt.Color(153, 0, 255));
        lblMesasDisponiveis.setText("jLabel15");

        javax.swing.GroupLayout jPanelMesLayout = new javax.swing.GroupLayout(jPanelMes);
        jPanelMes.setLayout(jPanelMesLayout);
        jPanelMesLayout.setHorizontalGroup(
            jPanelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMesLayout.createSequentialGroup()
                        .addComponent(cmbStatusMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jButton9)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10))
                    .addComponent(jLabel14))
                .addGap(59, 59, 59))
            .addGroup(jPanelMesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar3, javax.swing.GroupLayout.DEFAULT_SIZE, 16, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanelMesLayout.createSequentialGroup()
                .addGroup(jPanelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMesLayout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel4))
                    .addGroup(jPanelMesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cmbFiltroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblMesasDisponiveis)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelMesLayout.setVerticalGroup(
            jPanelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(jButton10)
                    .addComponent(cmbStatusMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumeroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelMesLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jScrollBar3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelMesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelMesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbFiltroMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMesasDisponiveis))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.add(jPanelMes, "telaMesas");

        jLabel5.setText("Produtos");

        cmbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Bebida", "Doce", "Salgado" }));
        cmbCategoria.addActionListener(this::cmbCategoriaActionPerformed);

        jLabel6.setText("Nome");

        jLabel7.setText("Preço");

        jLabel8.setText("Categoria");

        jLabel9.setText("Tempo de preparo");

        jButton1.setText("Editar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Excluir");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton4.setText("Salvar");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        tblProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Preço", "Categoria", "Tempo"
            }
        ));
        tblProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblProdutos);

        javax.swing.GroupLayout jPanelProLayout = new javax.swing.GroupLayout(jPanelPro);
        jPanelPro.setLayout(jPanelProLayout);
        jPanelProLayout.setHorizontalGroup(
            jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(346, 346, 346))
            .addGroup(jPanelProLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProLayout.createSequentialGroup()
                .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPreco)
                            .addGroup(jPanelProLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanelProLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(jPanelProLayout.createSequentialGroup()
                        .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTempo))))
                .addGap(39, 39, 39))
        );
        jPanelProLayout.setVerticalGroup(
            jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProLayout.createSequentialGroup()
                .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelProLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel6))
                    .addGroup(jPanelProLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton4))
                .addGap(20, 20, 20)
                .addGroup(jPanelProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 419, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.add(jPanelPro, "telaProdutos");

        jMenu1.setText("Menu");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pitica.png"))); // NOI18N
        jMenuItem1.setText("Comandas");
        jMenuItem1.addActionListener(this::jMenuItem1ActionPerformed);
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pitica.png"))); // NOI18N
        jMenuItem2.setText("Funcionários");
        jMenuItem2.addActionListener(this::jMenuItem2ActionPerformed);
        jMenu1.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pitica.png"))); // NOI18N
        jMenuItem4.setText("Mesas");
        jMenuItem4.addActionListener(this::jMenuItem4ActionPerformed);
        jMenu1.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pitica.png"))); // NOI18N
        jMenuItem5.setText("Produtos");
        jMenuItem5.addActionListener(this::jMenuItem5ActionPerformed);
        jMenu1.add(jMenuItem5);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "telaMesas");
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "telaFuncionarios");
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "telaProdutos");
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        CardLayout cl = (CardLayout) jPanel1.getLayout();
        cl.show(jPanel1, "telaComandas");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void cmbCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCategoriaActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
try {
        Produto p = new Produto();
        p.setNome(txtNome.getText());
        p.setPreco(Double.parseDouble(txtPreco.getText()));
        p.setCategoria(cmbCategoria.getSelectedItem().toString());
        p.setTempoPreparo(Integer.parseInt(txtTempo.getText()));

        ProdutoDAO dao = new ProdutoDAO();
        if (cmbCategoria.getSelectedIndex() == 0) {
    javax.swing.JOptionPane.showMessageDialog(this, "Por favor, escolha uma categoria válida!");
    return; // Para o código aqui
}
        dao.salvar(p);
        
        atualizarTudo();

        // Limpar campos após salvar
        limparCampos();
        carregarTabela(); // Atualiza a lista na tela
        
        javax.swing.JOptionPane.showMessageDialog(this, "Produto salvo com sucesso!");
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: Verifique se Preço e Tempo são números.");
    }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int linhaSelecionada = tblProdutos.getSelectedRow();
    
    if (linhaSelecionada == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um produto na tabela para excluir!");
        return;
    }
    
    // A trava de confirmação entra aqui:
    int op = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este produto?", "Confirmação", javax.swing.JOptionPane.YES_NO_OPTION);
    
    // Se o usuário clicar em "Sim" (YES_OPTION), o código entra no IF e exclui
    if (op == javax.swing.JOptionPane.YES_OPTION) {
        // Pega o ID que está na primeira coluna (índice 0) da linha selecionada
        int id = (int) tblProdutos.getValueAt(linhaSelecionada, 0);
        
        ProdutoDAO dao = new ProdutoDAO();
        dao.remover(id);
        
        atualizarTudo();
        
        carregarTabela(); // Atualiza a tabela
        limparCampos();   // Limpa os campos
        javax.swing.JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tblProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblProdutosMouseClicked
    int linha = tblProdutos.getSelectedRow();
    txtNome.setText(tblProdutos.getValueAt(linha, 1).toString());
    txtPreco.setText(tblProdutos.getValueAt(linha, 2).toString());
    cmbCategoria.setSelectedItem(tblProdutos.getValueAt(linha, 3).toString());
    txtTempo.setText(tblProdutos.getValueAt(linha, 4).toString());
    }//GEN-LAST:event_tblProdutosMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    int linha = tblProdutos.getSelectedRow();
    
    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um produto na tabela para editar!");
        return; 
    }
    
    int id = (int) tblProdutos.getValueAt(linha, 0);
    
    Produto p = new Produto();
    p.setIdProduto(id); // Importante!
    p.setNome(txtNome.getText());
    p.setPreco(Double.parseDouble(txtPreco.getText()));
    p.setCategoria(cmbCategoria.getSelectedItem().toString());
    p.setTempoPreparo(Integer.parseInt(txtTempo.getText()));
    
    ProdutoDAO dao = new ProdutoDAO();
    dao.alterar(p);
    
    atualizarTudo();
    
    carregarTabela();
    limparCampos();
    javax.swing.JOptionPane.showMessageDialog(this, "Produto atualizado!");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIdadeFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdadeFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdadeFunActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
if (cmbCargoFun.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um cargo válido!");
        return;
    }

    try {
        emanuellynogueiratrizotti.model.Funcionario f = new emanuellynogueiratrizotti.model.Funcionario();
        f.setNome(txtNomeFun.getText());
        f.setIdade(Integer.parseInt(txtIdadeFun.getText()));
        f.setCargo(cmbCargoFun.getSelectedItem().toString());

        emanuellynogueiratrizotti.dao.FuncionarioDAO dao = new emanuellynogueiratrizotti.dao.FuncionarioDAO();
        dao.salvar(f);

        atualizarTudo();
        
        limparCamposFuncionarios();
        carregarTabelaFuncionarios();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Funcionário salvo com sucesso!");
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: A idade deve ser um número inteiro.");
    }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void tblFuncionariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFuncionariosMouseClicked
int linha = tblFuncionarios.getSelectedRow();
    if (linha != -1) {
        txtNomeFun.setText(tblFuncionarios.getValueAt(linha, 1).toString());
        txtIdadeFun.setText(tblFuncionarios.getValueAt(linha, 2).toString());
        cmbCargoFun.setSelectedItem(tblFuncionarios.getValueAt(linha, 3).toString());
    }
    }//GEN-LAST:event_tblFuncionariosMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
int linha = tblFuncionarios.getSelectedRow();
    
    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um funcionário na tabela para editar!");
        return;
    }
    
    if (cmbCargoFun.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um cargo válido!");
        return;
    }

    try {
        int id = (int) tblFuncionarios.getValueAt(linha, 0);
        
        emanuellynogueiratrizotti.model.Funcionario f = new emanuellynogueiratrizotti.model.Funcionario();
        f.setIdFuncionario(id);
        f.setNome(txtNomeFun.getText());
        f.setIdade(Integer.parseInt(txtIdadeFun.getText()));
        f.setCargo(cmbCargoFun.getSelectedItem().toString());

        emanuellynogueiratrizotti.dao.FuncionarioDAO dao = new emanuellynogueiratrizotti.dao.FuncionarioDAO();
        dao.alterar(f);
        
        atualizarTudo();

        limparCamposFuncionarios();
        carregarTabelaFuncionarios();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Funcionário atualizado com sucesso!");
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: A idade deve ser um número inteiro.");
    }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
int linha = tblFuncionarios.getSelectedRow();
    
    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um funcionário na tabela para excluir!");
        return;
    }
    
    int op = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja realmente excluir este funcionário?", "Confirmação", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (op == javax.swing.JOptionPane.YES_OPTION) {
        int id = (int) tblFuncionarios.getValueAt(linha, 0);
        
        emanuellynogueiratrizotti.dao.FuncionarioDAO dao = new emanuellynogueiratrizotti.dao.FuncionarioDAO();
        dao.remover(id);
        
        atualizarTudo();
        
        limparCamposFuncionarios();
        carregarTabelaFuncionarios();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Funcionário excluído com sucesso!");
    }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void cmbFiltroMesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFiltroMesaActionPerformed
carregarTabelaMesas();
    }//GEN-LAST:event_cmbFiltroMesaActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
if (cmbStatusMesa.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, selecione um status inicial válido!");
        return;
    }
    
    try {
        emanuellynogueiratrizotti.model.Mesa m = new emanuellynogueiratrizotti.model.Mesa();
        m.setNumero(Integer.parseInt(txtNumeroMesa.getText()));
        m.setStatusOcupacao(cmbStatusMesa.getSelectedItem().toString());
        
        emanuellynogueiratrizotti.dao.MesaDAO dao = new emanuellynogueiratrizotti.dao.MesaDAO();
        dao.salvar(m);
        
        atualizarTudo();
        
        limparCamposMesas();
        carregarTabelaMesas(); // Atualiza a tabela e o contador de livres automaticamente
        
        javax.swing.JOptionPane.showMessageDialog(this, "Mesa cadastrada com sucesso!");
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: O número da mesa deve ser um valor inteiro.");
    }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void tblMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMesasMouseClicked
int linha = tblMesas.getSelectedRow();
    if (linha != -1) {
        txtNumeroMesa.setText(tblMesas.getValueAt(linha, 1).toString());
        cmbStatusMesa.setSelectedItem(tblMesas.getValueAt(linha, 2).toString());
    }
    }//GEN-LAST:event_tblMesasMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
int linha = tblMesas.getSelectedRow();
    
    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma mesa na tabela para editar!");
        return;
    }
    
    if (cmbStatusMesa.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, escolha um status válido para a atualização!");
        return;
    }
    
    try {
        int id = (int) tblMesas.getValueAt(linha, 0);
        
        // Agora criamos o objeto inteiro, igual nos Produtos e Funcionários
        emanuellynogueiratrizotti.model.Mesa m = new emanuellynogueiratrizotti.model.Mesa();
        m.setIdMesa(id);
        m.setNumero(Integer.parseInt(txtNumeroMesa.getText()));
        m.setStatusOcupacao(cmbStatusMesa.getSelectedItem().toString());
        
        emanuellynogueiratrizotti.dao.MesaDAO dao = new emanuellynogueiratrizotti.dao.MesaDAO();
        dao.alterar(m);
        
        atualizarTudo();
        
        limparCamposMesas();
        carregarTabelaMesas();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Mesa atualizada com sucesso!");
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: O número da mesa deve ser um valor inteiro.");
    }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
int linha = tblMesas.getSelectedRow();
    
    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma mesa na tabela para excluir!");
        return;
    }
    
    int op = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja realmente remover esta mesa?", "Confirmação", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (op == javax.swing.JOptionPane.YES_OPTION) {
        int id = (int) tblMesas.getValueAt(linha, 0);
        
        emanuellynogueiratrizotti.dao.MesaDAO dao = new emanuellynogueiratrizotti.dao.MesaDAO();
        dao.remover(id);
        
        atualizarTudo();
        
        limparCamposMesas();
        carregarTabelaMesas();
        
        javax.swing.JOptionPane.showMessageDialog(this, "Mesa removida com sucesso!");
    }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void cmbPgtoComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPgtoComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbPgtoComandaActionPerformed

    private void cmbCaixaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCaixaComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCaixaComandaActionPerformed

    private void txtGorjetaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGorjetaComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGorjetaComandaActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
if (cmbMesaComanda.getSelectedIndex() == 0 || cmbGarcomComanda.getSelectedIndex() == 0 || cmbCaixaComanda.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione a Mesa, Garçom e Caixa para abrir a conta!");
        return;
    }
    
    try {
        emanuellynogueiratrizotti.model.Comanda c = new emanuellynogueiratrizotti.model.Comanda();

        // Extrai apenas o número do ID antes do traço
        c.setIdMesa(Integer.parseInt(cmbMesaComanda.getSelectedItem().toString().split(" - ")[0]));
        c.setIdFuncionarioGarcom(Integer.parseInt(cmbGarcomComanda.getSelectedItem().toString().split(" - ")[0]));
        c.setIdFuncionarioCaixa(Integer.parseInt(cmbCaixaComanda.getSelectedItem().toString().split(" - ")[0]));

        emanuellynogueiratrizotti.dao.ComandaDAO dao = new emanuellynogueiratrizotti.dao.ComandaDAO();
        dao.abrirComanda(c);
        
        // Ocupa a mesa
emanuellynogueiratrizotti.dao.MesaDAO mesaDao = new emanuellynogueiratrizotti.dao.MesaDAO();
mesaDao.atualizarStatus(c.getIdMesa(), "Ocupada");

atualizarTudo();

        limparCamposComandas();
        carregarTabelaComandas();
        
        // Atualiza a caixa de mesas para remover a que acabou de ser ocupada
        preencherCombosEstrangeiros(); 
        
        javax.swing.JOptionPane.showMessageDialog(this, "Comanda aberta com sucesso!");
    } catch (HeadlessException | NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao abrir comanda: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
int linha = tblComandas.getSelectedRow();
    
    // Trava de segurança padrão que usamos em todos os botões
    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma comanda na tabela para gerenciar os itens!");
        return;
    }
    
    // Pega o ID da comanda na primeira coluna (índice 0)
    int idComandaSelecionada = (int) tblComandas.getValueAt(linha, 0);
    
    // Cria a nova tela de itens passando o ID obtido
    // (O 'this' passa a tela principal como 'pai' e o 'true' ativa o bloqueio modal)
    TelaItensComanda telaItens = new TelaItensComanda(this, true, idComandaSelecionada);
    
    // Faz a janelinha aparecer na tela
    telaItens.setLocationRelativeTo(this); // Centraliza a janela em cima da principal
    telaItens.setVisible(true);
    
    // Quando o usuário fechar a tela de itens, atualiza a tabela de comandas
    // (Caso o valor total ou status tenha mudado)
    carregarTabelaComandas();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
try {
        double valorMinimo = Double.parseDouble(txtValorFiltro.getText().replace(",", "."));
        
        emanuellynogueiratrizotti.dao.ComandaDAO dao = new emanuellynogueiratrizotti.dao.ComandaDAO();
        java.util.List<emanuellynogueiratrizotti.model.Comanda> lista = dao.listarComandasAcimaDeValor(valorMinimo);
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblComandas.getModel();
        modelo.setRowCount(0); // Limpa a tabela para mostrar só o filtro

        for (emanuellynogueiratrizotti.model.Comanda c : lista) {
            modelo.addRow(new Object[]{
                c.getIdComanda(),
                c.getIdMesa(),
                c.getStatus(),
                c.getFormaPgto(),
                c.getGorjeta()
            });
        }
        
        if (lista.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Nenhuma comanda encontrada com valor superior a R$ " + valorMinimo);
        }
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Digite um valor numérico válido para realizar o filtro.");
    }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void txtValorFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorFiltroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorFiltroActionPerformed

    private void tblComandasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblComandasMouseClicked
int linha = tblComandas.getSelectedRow();
    if (linha == -1) return;

    try {
        int idComanda = (int) tblComandas.getValueAt(linha, 0);
        
        int idMesa = 0;
        int numeroMesa = 0; // Nova variável para guardar o número da mesa
        int idGarcom = 0;
        int idCaixa = 0;
        String status = "";
        String pgto = "";
        double gorjeta = 0.0;
        
        // Fazemos um JOIN com a tabela mesas para descobrir o número real da mesa
        String sql = "SELECT c.id_mesa, m.numero as numero_mesa, c.status, c.forma_pgto, c.gorjeta, c.id_funcionario_garcom, c.id_funcionario_caixa " +
                     "FROM comandas c JOIN mesas m ON c.id_mesa = m.id_mesa " +
                     "WHERE c.id_comanda = ?";
                     
        try (java.sql.Connection conn = emanuellynogueiratrizotti.util.ConexaoDB.conectar();
             java.sql.PreparedStatement stmt = conn.prepareStatement(sql)) {
            
            stmt.setInt(1, idComanda);
            try (java.sql.ResultSet rs = stmt.executeQuery()) {
                if (rs.next()) {
                    idMesa = rs.getInt("id_mesa");
                    numeroMesa = rs.getInt("numero_mesa"); // Resgata o número
                    status = rs.getString("status");
                    pgto = rs.getString("forma_pgto");
                    gorjeta = rs.getDouble("gorjeta");
                    idGarcom = rs.getInt("id_funcionario_garcom");
                    idCaixa = rs.getInt("id_funcionario_caixa");
                }
            }
        }

        // Localiza a Mesa na Combobox
        boolean mesaEncontrada = false;
        for (int i = 0; i < cmbMesaComanda.getItemCount(); i++) {
            if (cmbMesaComanda.getItemAt(i).startsWith(idMesa + " - ")) {
                cmbMesaComanda.setSelectedIndex(i);
                mesaEncontrada = true;
                break;
            }
        }
        
        // SEGREDO AQUI: Se a mesa está ocupada, ela não está na combobox. Adicionamos ela agora!
        if (!mesaEncontrada && idMesa != 0) {
            String itemMesa = idMesa + " - Mesa " + numeroMesa;
            cmbMesaComanda.addItem(itemMesa);
            cmbMesaComanda.setSelectedItem(itemMesa);
        }

        // Localiza o Garçom
        for (int i = 0; i < cmbGarcomComanda.getItemCount(); i++) {
            if (cmbGarcomComanda.getItemAt(i).startsWith(idGarcom + " - ")) {
                cmbGarcomComanda.setSelectedIndex(i);
                break;
            }
        }

        // Localiza o Caixa
        for (int i = 0; i < cmbCaixaComanda.getItemCount(); i++) {
            if (cmbCaixaComanda.getItemAt(i).startsWith(idCaixa + " - ")) {
                cmbCaixaComanda.setSelectedIndex(i);
                break;
            }
        }

        cmbStatusComanda.setSelectedItem(status);
        if (pgto != null && !pgto.isEmpty()) {
            cmbPgtoComanda.setSelectedItem(pgto);
        } else {
            cmbPgtoComanda.setSelectedIndex(0); 
        }
        txtGorjetaComanda.setText(String.valueOf(gorjeta));

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao carregar dados da comanda: " + e.getMessage());
    }
    }//GEN-LAST:event_tblComandasMouseClicked

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
// Validação de Fechamento
    if (cmbStatusComanda.getSelectedItem().toString().equals("FECHADA") && cmbPgtoComanda.getSelectedIndex() == 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Para fechar a comanda, você deve selecionar a Forma de Pagamento!");
        return;
    }
        
    int linha = tblComandas.getSelectedRow();
    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma comanda na tabela para atualizar!");
        return;
    }

    try {
        // Resgata a mesa antiga da tabela antes de sobrescrever
        int idMesaAntiga = (int) tblComandas.getValueAt(linha, 1);
        
        emanuellynogueiratrizotti.model.Comanda c = new emanuellynogueiratrizotti.model.Comanda();
        c.setIdComanda((int) tblComandas.getValueAt(linha, 0));
        
        if (cmbMesaComanda.getSelectedIndex() == 0) {
            c.setIdMesa(idMesaAntiga);
        } else {
            c.setIdMesa(Integer.parseInt(cmbMesaComanda.getSelectedItem().toString().split(" - ")[0]));
        }
        
        c.setIdFuncionarioGarcom(Integer.parseInt(cmbGarcomComanda.getSelectedItem().toString().split(" - ")[0]));
        c.setIdFuncionarioCaixa(Integer.parseInt(cmbCaixaComanda.getSelectedItem().toString().split(" - ")[0]));
        c.setStatus(cmbStatusComanda.getSelectedItem().toString());
        c.setFormaPgto(cmbPgtoComanda.getSelectedItem().toString());
        
        String gorjetaStr = txtGorjetaComanda.getText().replace(",", ".");
        c.setGorjeta(Double.parseDouble(gorjetaStr));

        emanuellynogueiratrizotti.dao.ComandaDAO dao = new emanuellynogueiratrizotti.dao.ComandaDAO();
        dao.alterar(c);
        
        // Lógica de transição e liberação de mesas
        emanuellynogueiratrizotti.dao.MesaDAO mesaDao = new emanuellynogueiratrizotti.dao.MesaDAO();
        
        // Regra 1: Se o cliente trocou de mesa, libera a antiga imediatamente
        if (c.getIdMesa() != idMesaAntiga) {
            mesaDao.atualizarStatus(idMesaAntiga, "Disponível");
            
            // Se a comanda continua aberta, ocupa a mesa nova escolhida
            if (c.getStatus().equals("ABERTA")) {
                mesaDao.atualizarStatus(c.getIdMesa(), "Ocupada");
            }
        }

        // Regra 2: Liberação da mesa atual se a comanda foi FECHADA
        if (c.getStatus().equals("FECHADA")) {
            mesaDao.atualizarStatus(c.getIdMesa(), "Disponível");
        }

        // Atualização da interface
        limparCamposComandas();
        atualizarTudo(); // Isso vai chamar o preencherCombosEstrangeiros e resetar a tela
        
        javax.swing.JOptionPane.showMessageDialog(this, "Comanda atualizada com sucesso!");
        
    } catch (HeadlessException | NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: Verifique se todos os campos obrigatórios estão preenchidos corretamente.");
    }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
int linha = tblComandas.getSelectedRow();
    
    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma comanda para excluir!");
        return;
    }

    int op = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja realmente excluir esta comanda?", "Confirmação", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (op == javax.swing.JOptionPane.YES_OPTION) {
        int id = (int) tblComandas.getValueAt(linha, 0);
        emanuellynogueiratrizotti.dao.ComandaDAO dao = new emanuellynogueiratrizotti.dao.ComandaDAO();
        dao.remover(id);
        
        int idMesa = (int) tblComandas.getValueAt(linha, 1); // Pega o ID da mesa daquela comanda
emanuellynogueiratrizotti.dao.MesaDAO mesaDao = new emanuellynogueiratrizotti.dao.MesaDAO();
mesaDao.atualizarStatus(idMesa, "Disponível");

atualizarTudo();

        limparCamposComandas();
        carregarTabelaComandas();
        javax.swing.JOptionPane.showMessageDialog(this, "Comanda excluída com sucesso!");
    }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
try {
        // 1. Limpa o campo de texto do filtro
        txtValorFiltro.setText("");
        
        // 2. Instancia o DAO
        emanuellynogueiratrizotti.dao.ComandaDAO dao = new emanuellynogueiratrizotti.dao.ComandaDAO();
        
        // IMPORTANTE: Substitua 'listarTodas()' pelo nome real do método no seu DAO que busca tudo
        java.util.List<emanuellynogueiratrizotti.model.Comanda> lista = dao.listarTodas();
        
        // 3. Reseta o modelo da tabela
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblComandas.getModel();
        modelo.setRowCount(0); 

        // 4. Preenche a tabela com a lista completa
        for (emanuellynogueiratrizotti.model.Comanda c : lista) {
            modelo.addRow(new Object[]{
                c.getIdComanda(),
                c.getIdMesa(),
                c.getStatus(),
                c.getFormaPgto(),
                c.getGorjeta()
            });
        }
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao recarregar a tabela: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
// 1. Chama o DAO e a nova função de junção (JOIN)
    emanuellynogueiratrizotti.dao.ComandaDAO dao = new emanuellynogueiratrizotti.dao.ComandaDAO();
    java.util.List<String> lista = dao.listarComandasEGarcons();

    if (lista.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Nenhuma comanda encontrada para gerar o relatório.");
        return;
    }

    // 2. Monta o texto do relatório de forma estruturada
    StringBuilder relatorio = new StringBuilder();
    relatorio.append("--- RELATÓRIO DE COMANDAS E GARÇONS ---\n");
    relatorio.append("Requisito: Consulta com junção entre tabelas (JOIN)\n\n");
    
    for (String linha : lista) {
        relatorio.append(linha).append("\n");
    }

    // 3. Cria uma área de texto com barra de rolagem (limpa e profissional)
    javax.swing.JTextArea textArea = new javax.swing.JTextArea(relatorio.toString());
    textArea.setEditable(false);
    textArea.setFont(new java.awt.Font("Monospaced", java.awt.Font.PLAIN, 14)); // Fonte monoespaçada alinha melhor
    
    javax.swing.JScrollPane scrollPane = new javax.swing.JScrollPane(textArea);
    scrollPane.setPreferredSize(new java.awt.Dimension(450, 300));

    // 4. Exibe o resultado em um pop-up
    javax.swing.JOptionPane.showMessageDialog(this, scrollPane, "Resultado da Consulta (JOIN)", javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCaixaComanda;
    private javax.swing.JComboBox<String> cmbCargoFun;
    private javax.swing.JComboBox<String> cmbCategoria;
    private javax.swing.JComboBox<String> cmbFiltroMesa;
    private javax.swing.JComboBox<String> cmbGarcomComanda;
    private javax.swing.JComboBox<String> cmbMesaComanda;
    private javax.swing.JComboBox<String> cmbPgtoComanda;
    private javax.swing.JComboBox<String> cmbStatusComanda;
    private javax.swing.JComboBox<String> cmbStatusMesa;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelCom;
    private javax.swing.JPanel jPanelFun;
    private javax.swing.JPanel jPanelMes;
    private javax.swing.JPanel jPanelPro;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollBar jScrollBar2;
    private javax.swing.JScrollBar jScrollBar3;
    private javax.swing.JScrollBar jScrollBar4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblComandasAbertas;
    private javax.swing.JLabel lblMesasDisponiveis;
    private javax.swing.JTable tblComandas;
    private javax.swing.JTable tblFuncionarios;
    private javax.swing.JTable tblMesas;
    private javax.swing.JTable tblProdutos;
    private javax.swing.JTextField txtGorjetaComanda;
    private javax.swing.JTextField txtIdadeFun;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeFun;
    private javax.swing.JTextField txtNumeroMesa;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTempo;
    private javax.swing.JTextField txtValorFiltro;
    // End of variables declaration//GEN-END:variables

    // Método para limpar campos
    private void limparCampos() {
        txtNome.setText("");
        txtPreco.setText("");
        txtTempo.setText("");
        cmbCategoria.setSelectedIndex(0);
    }

    // Método para carregar a tabela
    private void carregarTabela() {
        ProdutoDAO dao = new ProdutoDAO();
        java.util.List<Produto> lista = dao.listarTodos();
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblProdutos.getModel();
        
        modelo.setRowCount(0); // Limpa a tabela
        
        for (Produto p : lista) {
            modelo.addRow(new Object[]{
                p.getIdProduto(), 
                p.getNome(), 
                p.getPreco(), 
                p.getCategoria(), 
                p.getTempoPreparo()
            });
        }
    }
    
    private void limparCamposFuncionarios() {
        txtNomeFun.setText("");
        txtIdadeFun.setText("");
        cmbCargoFun.setSelectedIndex(0); // Volta para "Selecione"
    }

    private void carregarTabelaFuncionarios() {
        emanuellynogueiratrizotti.dao.FuncionarioDAO dao = new emanuellynogueiratrizotti.dao.FuncionarioDAO();
        java.util.List<emanuellynogueiratrizotti.model.Funcionario> lista = dao.listarTodos();
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblFuncionarios.getModel();
        modelo.setRowCount(0); // Limpa a tabela
        
        for (emanuellynogueiratrizotti.model.Funcionario f : lista) {
            modelo.addRow(new Object[]{
                f.getIdFuncionario(), 
                f.getNome(), 
                f.getIdade(), 
                f.getCargo()
            });
        }
    }
    
    private void limparCamposMesas() {
        txtNumeroMesa.setText("");
        cmbStatusMesa.setSelectedIndex(0);
    }

    private void carregarTabelaMesas() {
        emanuellynogueiratrizotti.dao.MesaDAO dao = new emanuellynogueiratrizotti.dao.MesaDAO();
        
        // Verifica qual filtro está selecionado na caixa de pesquisa
        String filtro = "Todas";
        if (cmbFiltroMesa != null && cmbFiltroMesa.getSelectedItem() != null) {
            filtro = cmbFiltroMesa.getSelectedItem().toString();
        }
        
        java.util.List<emanuellynogueiratrizotti.model.Mesa> lista;
        if (filtro.equals("Todas")) {
            lista = dao.listarTodas();
        } else {
            lista = dao.listarPorStatus(filtro);
        }
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblMesas.getModel();
        modelo.setRowCount(0); // Limpa a tabela antes de recarregar
        
        for (emanuellynogueiratrizotti.model.Mesa m : lista) {
            modelo.addRow(new Object[]{
                m.getIdMesa(),
                m.getNumero(),
                m.getStatusOcupacao()
            });
        }
        
        // Atualiza dinamicamente o texto do JLabel com a contagem total do COUNT do banco
        int disponiveis = dao.contarMesasDisponiveis();
        lblMesasDisponiveis.setText("Mesas Livres Agora: " + disponiveis);
    }
    
    private void limparCamposComandas() {
        cmbMesaComanda.setSelectedIndex(0);
        cmbGarcomComanda.setSelectedIndex(0);
        cmbCaixaComanda.setSelectedIndex(0);
        cmbStatusComanda.setSelectedIndex(0);
        cmbPgtoComanda.setSelectedIndex(0);
        txtGorjetaComanda.setText("0.0");
    }

    private void carregarTabelaComandas() {
        emanuellynogueiratrizotti.dao.ComandaDAO dao = new emanuellynogueiratrizotti.dao.ComandaDAO();
        java.util.List<emanuellynogueiratrizotti.model.Comanda> lista = dao.listarTodas();

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblComandas.getModel();
        modelo.setRowCount(0);

        for (emanuellynogueiratrizotti.model.Comanda c : lista) {
            modelo.addRow(new Object[]{
                c.getIdComanda(),          // Coluna 0
                c.getIdMesa(),             // Coluna 1
                c.getStatus(),             // Coluna 2
                c.getFormaPgto(),          // Coluna 3
                c.getGorjeta(),            // Coluna 4
                c.getIdFuncionarioGarcom(),// Coluna 5 (dados extras para o clique usar)
                c.getIdFuncionarioCaixa()  // Coluna 6
            });
        }

        int abertas = dao.contarAbertas();
        lblComandasAbertas.setText("Comandas Abertas: " + abertas);
    }
    
    private void preencherCombosEstrangeiros() {
        // Limpa tudo antes de preencher para não duplicar se chamar de novo
        cmbMesaComanda.removeAllItems();
        cmbGarcomComanda.removeAllItems();
        cmbCaixaComanda.removeAllItems();
        
        // Adiciona a opção padrão no topo
        cmbMesaComanda.addItem("Selecione");
        cmbGarcomComanda.addItem("Selecione");
        cmbCaixaComanda.addItem("Selecione");

        // 1. Preenche as Mesas (Busca no banco APENAS as Disponíveis)
        emanuellynogueiratrizotti.dao.MesaDAO mesaDao = new emanuellynogueiratrizotti.dao.MesaDAO();
        java.util.List<emanuellynogueiratrizotti.model.Mesa> mesas = mesaDao.listarPorStatus("Disponível");
        for (emanuellynogueiratrizotti.model.Mesa m : mesas) {
            // Guarda o ID e o Número juntos visualmente (Ex: "1 - Mesa 5")
            cmbMesaComanda.addItem(m.getIdMesa() + " - Mesa " + m.getNumero());
        }

        // 2. Preenche Garçons e Caixas
        emanuellynogueiratrizotti.dao.FuncionarioDAO funcDao = new emanuellynogueiratrizotti.dao.FuncionarioDAO();
        java.util.List<emanuellynogueiratrizotti.model.Funcionario> funcionarios = funcDao.listarTodos();
        
        for (emanuellynogueiratrizotti.model.Funcionario f : funcionarios) {
            if (f.getCargo().equals("Garçom")) {
                cmbGarcomComanda.addItem(f.getIdFuncionario() + " - " + f.getNome());
            } else if (f.getCargo().equals("Caixa")) {
                cmbCaixaComanda.addItem(f.getIdFuncionario() + " - " + f.getNome());
            }
        }
    }
    
    public void atualizarTudo() {
    preencherCombosEstrangeiros();
    carregarTabelaComandas();
    carregarTabelaMesas();
    carregarTabela();
    carregarTabelaFuncionarios();
}
}
