/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author emanuelly
 */
public class TelaItensComanda extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaItensComanda.class.getName());

    // 1. Criamos a variável global para esta tela
    private int idComandaAtual;

    // 2. Adicionamos 'int idComanda' nos parâmetros do construtor
    public TelaItensComanda(java.awt.Frame parent, boolean modal, int idComanda) {
        super(parent, modal);
        initComponents();
        
        // 3. Salvamos o ID recebido e atualizamos o título da janela visualmente
        this.idComandaAtual = idComanda;
        this.setTitle("Gerenciando Itens da Comanda nº " + idComandaAtual);
        preencherCombosItens();
        carregarTabelaItens();
    }
    /**
     * Creates new form TelaItensComanda
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbProdutoItem = new javax.swing.JComboBox<>();
        txtQuantidadeItem = new javax.swing.JTextField();
        cmbCozinheiroItem = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblItens = new javax.swing.JTable();
        lblTotalComanda = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Itens");

        cmbProdutoItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        txtQuantidadeItem.setColumns(6);

        cmbCozinheiroItem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));

        jLabel2.setText("Produto");

        jLabel3.setText("Qtd.");

        jLabel4.setText("Cozinheiro");

        jButton1.setText("Remover");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Inserir");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        tblItens.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Produto", "Qtd", "Cozinheiro"
            }
        ));
        tblItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblItensMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblItens);

        lblTotalComanda.setFont(new java.awt.Font("Liberation Sans", 1, 18)); // NOI18N
        lblTotalComanda.setText("Total: R$0,00");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButton2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton1))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1)
                                            .addComponent(cmbProdutoItem, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jLabel2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtQuantidadeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(cmbCozinheiroItem, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(lblTotalComanda)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbProdutoItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtQuantidadeItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbCozinheiroItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTotalComanda)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
if (cmbProdutoItem.getSelectedIndex() == 0 || cmbCozinheiroItem.getSelectedIndex() == 0 || txtQuantidadeItem.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Preencha todos os campos para adicionar o item!");
        return;
    }

    try {
        emanuellynogueiratrizotti.model.Item i = new emanuellynogueiratrizotti.model.Item();
        
        // O ID da comanda já está salvo na memória da tela!
        i.setIdComanda(this.idComandaAtual);
        
        i.setIdProduto(Integer.parseInt(cmbProdutoItem.getSelectedItem().toString().split(" - ")[0]));
        i.setQtd(Integer.parseInt(txtQuantidadeItem.getText()));
        i.setIdFuncionarioCozinheiro(Integer.parseInt(cmbCozinheiroItem.getSelectedItem().toString().split(" - ")[0]));

        emanuellynogueiratrizotti.dao.ItemDAO dao = new emanuellynogueiratrizotti.dao.ItemDAO();
        dao.adicionarItem(i);

        txtQuantidadeItem.setText("");
        cmbProdutoItem.setSelectedIndex(0);
        carregarTabelaItens();
        
    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "A quantidade deve ser um número inteiro válido.");
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao adicionar item: " + e.getMessage());
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int linha = tblItens.getSelectedRow();
    
    if (linha == -1) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um item na tabela para remover!");
        return;
    }

    int op = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja remover este item do pedido?", "Confirmação", javax.swing.JOptionPane.YES_NO_OPTION);
    
    if (op == javax.swing.JOptionPane.YES_OPTION) {
        int idProduto = (int) tblItens.getValueAt(linha, 0);
        
        emanuellynogueiratrizotti.dao.ItemDAO dao = new emanuellynogueiratrizotti.dao.ItemDAO();
        dao.removerItem(this.idComandaAtual, idProduto);

        carregarTabelaItens();
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tblItensMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblItensMouseClicked
int linha = tblItens.getSelectedRow();
    if (linha != -1) {
        // 1. Pega o ID do Produto da tabela (Coluna 0) e procura no JComboBox
        String idProduto = tblItens.getValueAt(linha, 0).toString();
        for (int i = 0; i < cmbProdutoItem.getItemCount(); i++) {
            if (cmbProdutoItem.getItemAt(i).startsWith(idProduto + " - ")) {
                cmbProdutoItem.setSelectedIndex(i);
                break;
            }
        }
        
        // 2. Joga a quantidade de volta para o campo de texto (Coluna 1)
        txtQuantidadeItem.setText(tblItens.getValueAt(linha, 1).toString());
        
        // 3. Pega o ID do Cozinheiro da tabela (Coluna 2) e procura no JComboBox
        String idCozinheiro = tblItens.getValueAt(linha, 2).toString();
        for (int i = 0; i < cmbCozinheiroItem.getItemCount(); i++) {
            if (cmbCozinheiroItem.getItemAt(i).startsWith(idCozinheiro + " - ")) {
                cmbCozinheiroItem.setSelectedIndex(i);
                break;
            }
        }
    }
    }//GEN-LAST:event_tblItensMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TelaItensComanda dialog = new TelaItensComanda(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCozinheiroItem;
    private javax.swing.JComboBox<String> cmbProdutoItem;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalComanda;
    private javax.swing.JTable tblItens;
    private javax.swing.JTextField txtQuantidadeItem;
    // End of variables declaration//GEN-END:variables

    private void preencherCombosItens() {
        cmbProdutoItem.removeAllItems();
        cmbCozinheiroItem.removeAllItems();
        
        cmbProdutoItem.addItem("Selecione");
        cmbCozinheiroItem.addItem("Selecione");

        // 1. Preenche os Produtos
        emanuellynogueiratrizotti.dao.ProdutoDAO prodDao = new emanuellynogueiratrizotti.dao.ProdutoDAO();
        java.util.List<emanuellynogueiratrizotti.model.Produto> produtos = prodDao.listarTodos();
        for (emanuellynogueiratrizotti.model.Produto p : produtos) {
            cmbProdutoItem.addItem(p.getIdProduto() + " - " + p.getNome());
        }

        // 2. Preenche apenas os Cozinheiros
        emanuellynogueiratrizotti.dao.FuncionarioDAO funcDao = new emanuellynogueiratrizotti.dao.FuncionarioDAO();
        java.util.List<emanuellynogueiratrizotti.model.Funcionario> funcionarios = funcDao.listarTodos();
        for (emanuellynogueiratrizotti.model.Funcionario f : funcionarios) {
            if (f.getCargo().equals("Cozinheiro")) {
                cmbCozinheiroItem.addItem(f.getIdFuncionario() + " - " + f.getNome());
            }
        }
    }

    private void carregarTabelaItens() {
        emanuellynogueiratrizotti.dao.ItemDAO dao = new emanuellynogueiratrizotti.dao.ItemDAO();
        java.util.List<emanuellynogueiratrizotti.model.Item> lista = dao.listarPorComanda(this.idComandaAtual);

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tblItens.getModel();
        modelo.setRowCount(0);

        for (emanuellynogueiratrizotti.model.Item i : lista) {
            modelo.addRow(new Object[]{
                i.getIdProduto(),       // Coluna 0: Continua guardando o ID (essencial para o botão Excluir funcionar!)
                i.getNomeProduto(),     // Coluna 1: Agora exibe o TEXTO do produto para o usuário
                i.getQtd(),             // Coluna 2: Quantidade
                i.getNomeCozinheiro()   // Coluna 3: Agora exibe o TEXTO do funcionário
            });
        }
        // 1. Instancia o DAO da comanda para acessar a função matemática
    emanuellynogueiratrizotti.dao.ComandaDAO comandaDao = new emanuellynogueiratrizotti.dao.ComandaDAO();
    
    // 2. Puxa o total do banco (passando false para não embutir a gorjeta nesta tela de itens)
    double valorTotal = comandaDao.calcularTotal(this.idComandaAtual, false);
    
    // 3. Formata o número normal para o padrão de moeda do Brasil (ex: 15.5 vira 15,50)
    lblTotalComanda.setText(String.format("Total: R$ %.2f", valorTotal));
    }
}
